# permissions for end users to view things.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thing-viewer-role
rules:
- apiGroups:
  - mamachanko.com.mamachanko.com
  resources:
  - things
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mamachanko.com.mamachanko.com
  resources:
  - things/status
  verbs:
  - get
