# permissions for end users to edit things.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: thing-editor-role
rules:
- apiGroups:
  - mamachanko.com.mamachanko.com
  resources:
  - things
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mamachanko.com.mamachanko.com
  resources:
  - things/status
  verbs:
  - get
